name: Deploy to GitHub Packages  #El nombre del archivo

on:                #El trigger, en este caso cuando se hace push a la rama main
  push:
    branches:
      - main

jobs:               #Equipo donde va a desplegarse
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:                                         #Aquí se logea a github packages, las variables son automaticas, no hay que ingresarlas
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image                     #El etiquetado de la imagén con hash
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bankingsystem:latest
            ghcr.io/${{ github.repository_owner }}/bankingsystem:${{ env.SHORT_SHA }}

